import = ['C:\Users\cyadine\AppData\Roaming\alacritty\catppuccin\catppuccin-mocha.toml']
live_config_reload = true
working_directory = "C:/Users/cyadine"

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 17.0

[font.bold]
#family = "JetbrainsMono Nerd Font"
family = "NanumGothicCoding Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "NanumGothicCoding Nerd Font"
style = "Light Italic"

[font.normal]
family = "NanumGothicCoding Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[shell]
program = 'C:\Program Files\Git\bin\sh'
args = ['-l']


[window]
dynamic_padding = false
opacity = 0.9
startup_mode = "Windowed"
decorations = "full"
dimensions.columns = 115
dimensions.lines = 25

[scrolling]
history = 10000
multiplier = 3

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

