general:
  focus_follows_cursor: false
  cursor_follow_focus: false
  toggle_workspace_on_refocus: true
  show_floating_on_top: true
  floating_window_move_amount: "5%"
  window_animations: "unchanged"
  center_new_floating_windows: true

gaps:
  inner_gap: "10px"
  outer_gap: "10px"
focus_borders:
  active:
    enabled: true
    color: "#d3869b"
  inactive:
    enabled: true
    color: "#83a598"

bar:
  height: "25px"
  position: "top"
  opacity: 0.7
  background: "#000" #282828
  foreground: "#ebdbb2"
  font_family: "JetBrainsMono Nerd Font"
  # font_family: "NanumGothic Nerd Font"
  # font_family: "Maple Mono NF"
  font_size: "15px"
  padding: "0px 0px"
  offset_x: "0"
  offset_y: "0"
  border_radius: "0"
  component_separator:
    label_left: " | "
    label_center: " | "
  components_left:
    - type: "workspaces"
      focused_workspace_background: "#9d0006"  # Adjusted Gruvbox color (dark red)
      focused_workspace_foreground: "#ebdbb2"  # Gruvbox bright yellow
      displayed_workspace_background: "#282828"  # Gruvbox background
      default_workspace_background: "transparent"
    - type: "window title"
      foreground: "#ebdbb2"

  components_right:
    - type: "music"
      label_not_playing: ""
      label_paused: "▐▐ {song_title} - {artist_name} | "
      label_playing: "▶ {song_title} - {artist_name} | "
      max_title_length: 20
      max_artist_length: 20
    - type: "weather"
      latitude: 50.474800
      longitude: 4.183739
      label: "{temperature_celsius}°C "
      label_sun: "☀️ {temperature_celsius}°C "
      label_moon: "🌙{temperature_celsius}°C "
      label_cloud_moon: "🌙☁️ {temperature_celsius}°C "
      label_cloud_sun: "⛅ {temperature_celsius}°C "
      label_cloud_moon_rain: "🌙🌧️ {temperature_celsius}°C "
      label_cloud_sun_rain: "🌦️ {temperature_celsius}°C "
      label_cloud_rain: "🌧️ {temperature_celsius}°C "
      label_snow_flake: "❄️ {temperature_celsius}°C "
      label_thunderstorm: "⚡{temperature_celsius}°C "
      label_cloud: "☁️ {temperature_celsius}°C "
    - type: "clock"
      foreground: "#ebdbb2"
      time_formatting: "dd/MM/yy H:mm"
    - type: "system tray"
      padding: "5px 0px"


workspaces:
  - name: "1"
    display_name: "1"
    keep_alive: true
    bind_to_monitor: 1
  - name: "2"
    display_name: "2"
    keep_alive: true
    bind_to_monitor: 2
  - name: "3"
    display_name: "3"
    keep_alive: false
    bind_to_monitor: 1
  - name: "4"
    display_name: "4"
    keep_alive: false
    bind_to_monitor: 1
  - name: "5"
    display_name: "5"
    keep_alive: false
    bind_to_monitor: 1
  - name: "6"
    display_name: "6"
    keep_alive: false
    bind_to_monitor: 1


keybindings:
  - command: "focus left"
    bindings: ["Alt+H", "Alt+Left"]
  - command: "focus right"
    bindings: ["Alt+J", "Alt+Right"]
  - command: "focus up"
    bindings: ["Alt+K", "Alt+Up"]
  - command: "focus down"
    bindings: ["Alt+L", "Alt+Down"]

  - command: "move left"
    bindings: ["Alt+Shift+H", "Alt+Shift+Left"]
  - command: "move right"
    bindings: ["Alt+Shift+J", "Alt+Shift+Right"]
  - command: "move up" 
    bindings: ["Alt+Shift+K", "Alt+Shift+Up"]
  - command: "move down"
    bindings: ["Alt+Shift+L", "Alt+Shift+Down"]


# Change window size 
  - command: "resize width -2%"
    binding: "Alt+U"
  - command: "resize width +2%"
    binding: "Alt+I"
    
  # - command: "resize height +2%"
  #   binding: "Alt+P"
  # - command: "resize height -2%"
  #   binding: "Alt+O"
    
  # Change the focused window to be floating / tiling
  - command: "toggle floating"
    binding: "Alt+Shift+Space"

  # Change the focused window to be maximized / unmaximized
  - command: "toggle maximized"
    binding: "Alt+F"

  # Minimize focused window
  - command: "set minimized"
    binding: "Alt+M"

  # Close focused window
  - command: "close"
    binding: "Alt+Q"

  # Exit GlazeWM
  - command: "exit wm"
    binding: "Alt+Shift+E"

  # Reload configuration file
  - command: "reload config"
    binding: "Alt+Shift+R"

  # Start alacritty
  #  - command: "exec 'C:\\Program Files\\Alacritty\\alacritty.exe'"
  - command: "exec 'C:\\Users\\cyadine\\AppData\\Local\\Microsoft\\WindowsApps\\wt.exe'"
    binding: "Alt+Enter"
  # Start Explorer
  - command: "exec 'C:\\Windows\\explorer.exe'"
    binding: "Alt+E"
  # Start ProcessHacker
  - command: "exec 'E:\\Divers\\Processhacker2\\ProcessHacker.exe'"
    binding: "Alt+Shift+P"
  - command: "exec 'C:\\Windows\\System32\\Taskmgr.exe'"
    binding: "Alt+P"
  # start browser (Arc)
  # - command: "exec 'C:\\Users\\cyadine\\AppData\\Local\\Microsoft\\WindowsApps\\Arc.exe'"
  #   binding: "Alt+B"
  # - command: "exec 'C:\\Program Files\\BraveSoftware\\Brave-Browser\\Application\\brave.exe'"
    #  binding: "Alt+B"
  - command: "exec firefox"
    binding: "Alt+B"

  # Workspace bindings
  - command: "focus workspace 1"
    binding: "Alt+1"
  - command: "focus workspace 2"
    binding: "Alt+2"
  - command: "focus workspace 3"
    binding: "Alt+3"
  - command: "focus workspace 4"
    binding: "Alt+4"
  - command: "focus workspace 5"
    binding: "Alt+5"
  - command: "focus workspace 6"
    binding: "Alt+6"
    
  - commands: ["move to workspace 1"]
    binding: "Alt+Shift+1"
  - commands: ["move to workspace 2"]
    binding: "Alt+Shift+2"
  - commands: ["move to workspace 3"]
    binding: "Alt+Shift+3"
  - commands: ["move to workspace 4"]
    binding: "Alt+Shift+4"
  - commands: ["move to workspace 5"]
    binding: "Alt+Shift+5"
  - commands: ["move to workspace 6"]
    binding: "Alt+Shift+6"


window_rules:
# Move app to workspace
  - command: "move to workspace 1"
    match_process_name: "brave"
  - command: "move to workspace 1"
    match_process_name: "firefox"
  - command: "move to workspace 1"
    match_process_name: "Arc"
  - command: "move to workspace 2"
    match_process_name: "Discord"

  - command: "ignore"
    match_process_name: "/Taskmgr|ScreenClippingHost/"
  - command: "set floating"
    match_class_name: "#32770"
  - command: "ignore"
    match_title: "[Pp]icture.in.[Pp]icture"
    match_class_name: "Chrome_WidgetWin_1|MozillaDialogClass"
  - command: "ignore"
    match_process_name: "RiotClientUx"
  - command: "ignore"
    match_process_name: "LeagueClient"
  - command: "ignore"
    match_process_name: "LeagueClientUx"
  - command: "ignore"
    match_process_name: "League of Legends"
  - command: "ignore"
    match_process_name: "Content Manager"
  - command: "ignore"
    match_process_name: "osu!"
  - command: "ignore"
    match_process_name: "TabletDriverGUI"
  - command: "ignore"
    match_process_name: "SoundSpacePlus"
  - command: "ignore" 
    match_title: "Media viewer"
  - command: "ignore"
    match_process_name: "Lunar Client"
  - command: "ignore"
    match_process_name: "Javaw"
  - command: "ignore"
    match_process_name: "javaw"
  - command: "ignore"
    match_process_name: "Modrinth App"
  - command: "set floating"
    match_process_name: "alacritty"
  - command: "ignore"
    match_process_name: "Lightshot"
  - command: "set floating"
    match_process_name: "mpv"
  - command: "set floating"
    match_process_name: "Overwolf"
  - command: "set floating"
    match_process_name: "OverwolfBrowser"
  - command: "set floating"
    match_process_name: "OverwolfHelper"
  - command: "set floating"
    match_process_name: "OverwolfHelper64"
  - command: "set floating"
    match_process_name: "Porofessor.gg"
  - command: "set floating"
    match_process_name: "ShareX"
  - command: "set floating"
    match_process_name: "Motrix"
  - command: "set floating"
    match_process_name: "Cyberduck"
  - command: "ignore"
    match_process_name: "ts3client_win64"
  - command: "set floating"
    match_process_name: "7zFM"
